"""Boss直聘 Web 端 DOM 选择器与页面读取。"""

from .selectors import (
    CommunicationQuotaNotice,
    WebSelectionError,
    build_card_fingerprint,
    build_conversation_fingerprint,
    click_expectation,
    click_positions_tab,
    expectation_is_active,
    extract_chat_conversations,
    extract_chat_messages,
    extract_chat_system_notes,
    extract_job_cards,
    find_card_element,
    find_chat_entry,
    find_conversation_element,
    find_conversation_open_target,
    find_conversation_operation_element,
    find_expectation_element,
    find_greeting_editor,
    find_resume_send_entry,
    find_send_button,
    iter_job_card_dicts,
    parse_job_intents,
    read_current_chat_identity,
    read_current_chat_job_info,
    read_current_chat_job_name,
    read_communication_quota_notice,
    read_message_unread_count,
    resume_request_accept_button,
    select_job_card_inline,
)
from .page_reader import align_detail_identity, read_job_detail

__all__ = [
    "CommunicationQuotaNotice",
    "WebSelectionError",
    "build_card_fingerprint",
    "build_conversation_fingerprint",
    "click_expectation",
    "click_positions_tab",
    "expectation_is_active",
    "extract_chat_conversations",
    "extract_chat_messages",
    "extract_chat_system_notes",
    "extract_job_cards",
    "find_card_element",
    "find_chat_entry",
    "find_conversation_element",
    "find_conversation_open_target",
    "find_conversation_operation_element",
    "find_expectation_element",
    "find_greeting_editor",
    "find_resume_send_entry",
    "find_send_button",
    "iter_job_card_dicts",
    "parse_job_intents",
    "read_current_chat_identity",
    "read_current_chat_job_info",
    "read_current_chat_job_name",
    "read_communication_quota_notice",
    "read_message_unread_count",
    "read_job_detail",
    "resume_request_accept_button",
    "select_job_card_inline",
    "align_detail_identity",
]
